PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE config_server
(

    id               INTEGER PRIMARY KEY,

    config_world     VARCHAR(20),

    config_type      VARCHAR(10),

    config_name      VARCHAR(10),

    config_data      VARCHAR(100),

    config_data_type VARCHAR(10),

    config_desc      VARCHAR(500)

);
INSERT INTO config_server VALUES(1,'1','world','channelIds','1,2,3,4,5','String','频道id');
INSERT INTO config_server VALUES(2,'1','world','serverMessage','欢迎来到小睡冒险岛!','String','游戏内滚动信息');
INSERT INTO config_server VALUES(3,'1','world','eventMessage','小睡1区!','String','选择大区展示的信息');
INSERT INTO config_server VALUES(4,'1','world','recommendedMessage','','String','推荐信息');
INSERT INTO config_server VALUES(5,'1','world','expRate','1','Integer','经验倍率');
INSERT INTO config_server VALUES(6,'1','world','mesoRate','1','Integer','金币倍率');
INSERT INTO config_server VALUES(7,'1','world','dropRate','1','Integer','掉落倍率');
INSERT INTO config_server VALUES(8,'1','world','bossDropRate','1','Integer','BOSS掉落倍率');
INSERT INTO config_server VALUES(9,'1','world','questRate','1','Integer','完成任务的经验和金币倍率');
INSERT INTO config_server VALUES(10,'1','world','travelRate','1','Integer','旅行花费的时间倍率');
INSERT INTO config_server VALUES(11,'1','world','fishingRate','1','Integer','钓鱼倍率');
INSERT INTO config_server VALUES(12,'*','database','dbUrl','jdbc:mysql://127.0.0.1:3306/napms?useUnicode=true&characterEncoding=gbk&tinyInt1isBit=false','String','数据库连接url');
INSERT INTO config_server VALUES(13,'*','database','dbUser','root','String','数据库连接用户名');
INSERT INTO config_server VALUES(14,'*','database','dbPass','root','String','数据库连接密码');
INSERT INTO config_server VALUES(15,'*','database','dbMaxConnect','0','Integer','数据库连接池最大连接数');
INSERT INTO config_server VALUES(16,'*','world','channelLoad','100','Integer','频道最大人数');
INSERT INTO config_server VALUES(17,'*','world','channelLocks','10','String','每个频道锁数量');
INSERT INTO config_server VALUES(18,'*','game','monsterRespawn','10000','Long','怪物刷新间隔，单位ms');
INSERT INTO config_server VALUES(19,'*','server','timeTaskPurge','300000','Long','清除所有等待的任务间隔，避免任务一直不执行死锁、内存泄漏等，单位ms');
INSERT INTO config_server VALUES(20,'*','game','rankRefresh','3600000','Long','排名刷新间隔，单位ms');
INSERT INTO config_server VALUES(21,'*','game','couponRefresh','3600000','Long','现金券相关的刷新间隔，单位ms');
INSERT INTO config_server VALUES(22,'*','server','commonRefresh','777','Long','通用定时任务刷新间隔');
INSERT INTO config_server VALUES(23,'*','game','picEnabled','false','Boolean','是否开启PIC码校验');
INSERT INTO config_server VALUES(24,'*','game','pinEnabled','false','Boolean','是否开启PIN码校验');
INSERT INTO config_server VALUES(25,'*','game','picExpiration','20','Integer','pic码失效时间，单位min');
INSERT INTO config_server VALUES(26,'*','game','pinExpiration','15','Integer','pin码失效时间，单位min');
INSERT INTO config_server VALUES(27,'*','game','automaticRegister','true','Boolean','账户不存在是否自动创建');
INSERT INTO config_server VALUES(28,'*','game','bcryptMigration','true','Boolean','是否开启新版加密机制');
INSERT INTO config_server VALUES(29,'*','game','collectiveCharacterSlot','false','Boolean','角色槽全大区通用');
INSERT INTO config_server VALUES(30,'*','game','deterredMultiClient','false','Boolean','是否允许多开');
INSERT INTO config_server VALUES(31,'*','game','maxAllowedAccountHwId','10','Integer','一个账号最多能支持的机器码登录');
INSERT INTO config_server VALUES(32,'*','game','maxAccountLoginAttempt','15','Integer','一个账户最多能登录失败多少次');
INSERT INTO config_server VALUES(33,'*','game','loginAttemptDuration','120','Integer','登录失败达到上限后禁止登录多少秒');
INSERT INTO config_server VALUES(34,'*','server','host','127.0.0.1','String','服务器ip');
INSERT INTO config_server VALUES(35,'*','server','localServer','true','Boolean','是否为本地服务，如果是127.0.0.1就选true，其他为false');
INSERT INTO config_server VALUES(36,'*','game','useCustomKeySet','false','Boolean','创建角色后，是否允许自定义键位');
INSERT INTO config_server VALUES(37,'*','debug','useDebug','false','Boolean','是否开启debug');
INSERT INTO config_server VALUES(38,'*','debug','debugLevel','simple','String','debug展示的信息，simple-简单，more-详细，full-完整');
INSERT INTO config_server VALUES(39,'*','debug','useThreadTracker','false','Boolean','是否开启线程追踪，内存消耗会暴增，仅调试使用');
INSERT INTO config_server VALUES(40,'*','game','useSupplyRateCoupons','true','Boolean','是否允许通过现金商店出售利率券');
INSERT INTO config_server VALUES(41,'*','server','useIpValidation','false','Boolean','是否启用登录时IP检查功能');
INSERT INTO config_server VALUES(42,'*','server','useCharacterAccountCheck','false','Boolean','是否启用登录时账户id检查功能');
INSERT INTO config_server VALUES(43,'*','server','useMaxRange','true','Boolean','是否监听全地图事件');
INSERT INTO config_server VALUES(44,'*','game','useMaxRangeEchoOfHero','true','Boolean','是否使用英雄的最大距离回声');
INSERT INTO config_server VALUES(45,'*','game','useMts','false','Boolean','是否开启拍卖行，关闭则启用拍卖行菜单');
INSERT INTO config_server VALUES(46,'*','game','useCpq','true','Boolean','是否开启嘉年华CPQ');
INSERT INTO config_server VALUES(47,'*','game','useAutoHideGm','true','Boolean','GM是否自动隐身');
INSERT INTO config_server VALUES(48,'*','game','useFixedRatioPoolUpdate','false','Boolean','是否固定比例更新血量和蓝量');
INSERT INTO config_server VALUES(49,'*','game','useFamilySystem','true','Boolean','是否使用家族系统');
INSERT INTO config_server VALUES(50,'*','game','useDuey','true','Boolean','是否启用Duey，特殊npc');
INSERT INTO config_server VALUES(51,'*','game','useRandomizePoolGain','false','Boolean','获取血量和蓝量是否随机化，洗血会用到');
INSERT INTO config_server VALUES(52,'*','game','useItemSort','true','Boolean','是否启用物品排序、合并');
INSERT INTO config_server VALUES(53,'*','game','useItemSortByName','false','Boolean','排序根据物品名称而不是id');
INSERT INTO config_server VALUES(54,'*','game','useParTyForStarters','false','Boolean','新手玩家是否能发起组队');
INSERT INTO config_server VALUES(55,'*','game','useServerAutoAssigner','true','Boolean','是否使用heavenms内置的自动加点，会结合职业的次要属性来分配属性点');
INSERT INTO config_server VALUES(56,'*','game','useAutoAssignSecondaryCap','true','Boolean','次要属性到达职业上限后不再分配，开始内置的自动加点才生效');
INSERT INTO config_server VALUES(57,'*','game','useAutoAssignStartersAp','false','Boolean','新手是否自动分配属性，仅当新手允许分配属性时生效');
INSERT INTO config_server VALUES(58,'*','game','useStartingAp4','true','Boolean','使用早期gms 4/4/4的起始数据。为了克服AP不足的问题，第1次/第2次任务提升为4AP/5AP');
INSERT INTO config_server VALUES(59,'*','game','useAutoBan','false','Boolean','是否检查玩家作弊行为，并自动阻止');
INSERT INTO config_server VALUES(60,'*','game','useAutoBanLog','true','Boolean','是否检查玩家作弊行为，并记录日志');
INSERT INTO config_server VALUES(61,'*','game','useAutoSave','true','Boolean','是否自动保存，1h保存一次');
INSERT INTO config_server VALUES(62,'*','game','useRefreshRankMove','true','Boolean','是否刷新排名升降');
INSERT INTO config_server VALUES(63,'*','game','useEnforceAdminAccount','false','Boolean','是否强制本地客户端将具有GM字符的帐户视为GM帐户');
INSERT INTO config_server VALUES(64,'*','game','useEnforceNoviceExpRate','true','Boolean','新手倍率恒定1倍，避免还没转职就十几级了');
INSERT INTO config_server VALUES(65,'*','game','useEnforceHpMpSwap','false','Boolean','强制玩家分配给HP/MP的属性只能重新分配到HP/MP，洗血相关');
INSERT INTO config_server VALUES(66,'*','game','useEnforceMobLevelRange','false','Boolean','比被杀怪物低N级的玩家将不会从打败它中获得任何经验');
INSERT INTO config_server VALUES(67,'*','game','useEnforceJobLevelRange','true','Boolean','达到等级没有转职无法获取经验');
INSERT INTO config_server VALUES(68,'*','game','useEnforceJobSpRange','false','Boolean','玩家技能点等级的上限是他们当前的等级所能获得的总数。更换job（职业）后，丢失的技能点将被找回');
INSERT INTO config_server VALUES(69,'*','game','useEnforceItemSuggestion','false','Boolean','强制现金商店总是显示预设的商品，而不是玩家定义的商品');
INSERT INTO config_server VALUES(70,'*','game','useEnforceUnMerchAbleCash','false','Boolean','玩家不允许销售现金物品，丢掉后立刻消失');
INSERT INTO config_server VALUES(71,'*','game','useEnforceUnMerchAblePet','false','Boolean','玩家不允许销售宠物，丢掉后立刻消失');
INSERT INTO config_server VALUES(72,'*','game','useEnforceMerchantSave','false','Boolean','与商店的交易动作会触发数据的保存');
INSERT INTO config_server VALUES(73,'*','game','useEnforceMDoorPosition','false','Boolean','迫使神秘之门在附近产生');
INSERT INTO config_server VALUES(74,'*','game','useSpawnLootOnAnimation','false','Boolean','战利品在怪物被击杀一段时间后出现，而不是立即出现');
INSERT INTO config_server VALUES(75,'*','game','useSpawnRelevantLoot','false','Boolean','只生成玩家和队员可拾取的战利品');
INSERT INTO config_server VALUES(76,'*','game','useErasePermitOnOpenShop','true','Boolean','玩家在开店后会立即消耗许可证');
INSERT INTO config_server VALUES(77,'*','game','useEraseUnTradeAbleDrop','false','Boolean','不可交易的物品在掉落后立即消失');
INSERT INTO config_server VALUES(78,'*','game','useErasePetOnExpiration','false','Boolean','宠物到期后直接删除');
INSERT INTO config_server VALUES(79,'*','game','useBuffMostSignificant','true','Boolean','使用同类增益道具时，玩家保留使用列表中最高的属性提升，而不是覆盖属性');
INSERT INTO config_server VALUES(80,'*','game','maxMonitoredBuffStats','5','Integer','覆盖的属性buff失效后，保留被覆盖的buff个数');
INSERT INTO config_server VALUES(81,'*','game','useBuffEverlasting','false','Boolean','无限buff时间');
INSERT INTO config_server VALUES(82,'*','game','useMultipleSameEquipDrop','true','Boolean','允许相同的装备掉落多份，掉落的份数取决于定义的掉落物数量');
INSERT INTO config_server VALUES(83,'*','game','useBanishAbleTownScroll','false','Boolean','');
INSERT INTO config_server VALUES(84,'*','game','useEnableFullRespawn','false','Boolean','是否按最大数量刷新，刷新怪物的数量是否按地图人数决定，最大6人');
INSERT INTO config_server VALUES(85,'*','game','useEnableChatLog','false','Boolean','记录聊天日志');
INSERT INTO config_server VALUES(86,'*','game','useRebirthSystem','false','Boolean','是否开启转生系统');
INSERT INTO config_server VALUES(87,'*','game','useMapOwnershipSystem','false','Boolean','是否开启地图所有权系统');
INSERT INTO config_server VALUES(88,'*','game','useNpcScriptable','true','Boolean','是否启用服务端预置的NPC脚本');
INSERT INTO config_server VALUES(89,'*','game','useOldGmsStyledPqNpcs','true','Boolean','使组队任务npc具有与旧GMS风格相似的行为，跳过PQ的信息，并立即尝试注册队伍');
INSERT INTO config_server VALUES(90,'*','game','useEnableCustomNpcScript','false','Boolean','是否启用heavenms自定义的npc脚本');
INSERT INTO config_server VALUES(91,'*','game','useEnableSoloExpeditions','true','Boolean','允许玩家单人进入副本');
INSERT INTO config_server VALUES(92,'*','game','useEnableDailyExpeditions','false','Boolean','启用每日副本入场限制');
INSERT INTO config_server VALUES(93,'*','game','useEnableRecallEvent','false','Boolean','使下线的玩家能够重新登录他们在退出之前进入的最后一个事件实例。仅在事件尚未清除或处理时有效');
INSERT INTO config_server VALUES(94,'*','game','useAnnounceShopItemSold','false','Boolean','玩家商店物品被卖，是否通知所有人');
INSERT INTO config_server VALUES(95,'*','game','useAnnounceChangeJob','false','Boolean','更换职业时自动发送消息给好友');
INSERT INTO config_server VALUES(96,'*','game','useJointCashShopInventory','false','Boolean','允许玩家多个角色间共享现金商城库存，不过独特的现金物品不会出现在其中');
INSERT INTO config_server VALUES(97,'*','game','useClearOutdatedCoupons','true','Boolean','是否自动清除过期的点券');
INSERT INTO config_server VALUES(98,'*','game','allowCashShopNameChange','true','Boolean','现金商城是否允许购买改名卡');
INSERT INTO config_server VALUES(99,'*','game','allowCashShopWorldTransfer','true','Boolean','现金商城是否允许购买瞬移石');
INSERT INTO config_server VALUES(100,'*','game','useMakerPermissiveAtkUp','true','Boolean','非武器装备能否强化攻击');
INSERT INTO config_server VALUES(101,'*','game','useMakerFeeHeuristics','true','Boolean','制造成本是否计算辅助剂费用');
INSERT INTO config_server VALUES(102,'*','game','useStarterMerge','false','Boolean','是否开启装备融合');
INSERT INTO config_server VALUES(103,'*','game','blockGenerateCashItem','false','Boolean','是否允许添加现金物品，或者添加现金掉落');
INSERT INTO config_server VALUES(104,'*','game','useWholeServerRanking','false','Boolean','是否启用全服排名，而不是大区排名');
INSERT INTO config_server VALUES(105,'*','game','equipExpRate','1.0','Double','装备经验倍率, 线性增长. 默认1.0 (大约100-200个同等级怪物可以让装备升级)');
INSERT INTO config_server VALUES(106,'*','game','pqBonusExpRate','0.5','Double','组队任务经验倍率');
INSERT INTO config_server VALUES(107,'*','game','partyBonusExpRate','1.0','Double','组队经验倍率');
INSERT INTO config_server VALUES(108,'*','game','expSplitLevelInterval','5','Integer','组队非攻击玩家必须在N级之间才能获取到怪物经验');
INSERT INTO config_server VALUES(109,'*','game','expSplitMvpMod','0.2','Double','组队怪物经验，队长的经验比例');
INSERT INTO config_server VALUES(110,'*','game','expSplitCommonMod','0.8','Double','组队分配怪物经验，队员分配的经验比例');
INSERT INTO config_server VALUES(111,'*','game','timezone','GMT+8','String','服务时区');
INSERT INTO config_server VALUES(112,'*','game','maxAp','32767','Integer','允许获得的最大属性点');
INSERT INTO config_server VALUES(113,'*','game','maxEventLevels','8','Integer','最大的事件奖励等级，每个等级获取到的事件奖励会有差异');
INSERT INTO config_server VALUES(114,'*','game','reopenNpcInterval','500','Long','与NPC交谈的最小时间间隔，默认500ms');
INSERT INTO config_server VALUES(115,'*','game','totMobQuestRequirement','0','Integer','TOT任务需要的怪物数，0为默认999ms');
INSERT INTO config_server VALUES(116,'*','game','mobReactorRefreshTime','0','Integer','0为默认30000ms');
INSERT INTO config_server VALUES(117,'*','game','partySearchReentryLimit','10','Integer','允许队长被组队搜索到的次数');
INSERT INTO config_server VALUES(118,'*','game','nameChangeCoolDown','2592000000','Long','改名的冷却时间，默认30天，单位ms');
INSERT INTO config_server VALUES(119,'*','game','worldTransferCoolDown','2592000000','Long','转区的冷却时间，默认30天，单位ms');
INSERT INTO config_server VALUES(120,'*','game','instantNameChange','false','Boolean','改名是否在服务重启后生效');
INSERT INTO config_server VALUES(121,'*','game','itemExpireTime','180000','Long','掉落物的消失时间，默认3min');
INSERT INTO config_server VALUES(122,'*','game','kiteExpireTime','3600000','Long','现金物品的消失时间，默认1h');
INSERT INTO config_server VALUES(123,'*','game','itemMonitorTime','300000','Long','地图不存在的物品检查，定时任务时间间隔，默认5min');
INSERT INTO config_server VALUES(124,'*','server','lockMonitorTime','30000','Long','服务器锁的失效时间，避免死锁，默认30s');
INSERT INTO config_server VALUES(125,'*','game','itemExpireCheck','10000','Long','定时检查掉落物是否需要消失，默认10s');
INSERT INTO config_server VALUES(126,'*','game','itemLimitOnMap','200','Integer','地图最多能存在多少个物品');
INSERT INTO config_server VALUES(127,'*','game','mapVisitedSize','5','Integer','最多保留每个玩家待过的最近n个地图，用于恢复和更新玩家的物品掉落的记录，默认5');
INSERT INTO config_server VALUES(128,'*','game','mapDamageOvertimeInterval','5000','Long','地图伤害的时间间隔，默认5s，有些地图会对玩家持续造成伤害');
INSERT INTO config_server VALUES(129,'*','game','mobStatusMonitorProc','200','Long','在怪物仇恨监测时间表上每次触发之间的毫秒频率');
INSERT INTO config_server VALUES(130,'*','game','mobStatusMonitorLife','84','Long','闲置触发计数怪物仇恨监控器允许在那里，然后关闭它由于不活动');
INSERT INTO config_server VALUES(131,'*','game','mobStatusAggroPersistence','2','Long','空闲触发依赖于一个怪的仇恨更新来保持跟随当前的玩家，因为他/她是主要的伤害攻击');
INSERT INTO config_server VALUES(132,'*','game','mobStatusAggroInterval','5000','Long','怪物仇恨值更新之间的间隔，默认5s');
INSERT INTO config_server VALUES(133,'*','game','useAutoAggroNearby','false','Boolean','当玩家接近怪物时，它们会开始跟随玩家');
INSERT INTO config_server VALUES(134,'*','game','usePerfectGmScroll','true','Boolean','GM使用卷轴不会失败');
INSERT INTO config_server VALUES(135,'*','game','usePerfectScrolling','false','Boolean','砸卷失败不消耗次数');
INSERT INTO config_server VALUES(136,'*','game','useEnhancedChScroll','false','Boolean','混沌卷轴能提供更好的属性');
INSERT INTO config_server VALUES(137,'*','game','useEnhancedCrafting','false','Boolean','锻造的装备会被使用一次混沌卷轴');
INSERT INTO config_server VALUES(138,'*','game','useEnhancedClnSlate','false','Boolean','白卷也可以用于恢复成功使用的槽');
INSERT INTO config_server VALUES(139,'*','game','scrollChanceRolls','1','Integer','卷轴成功率倍数');
INSERT INTO config_server VALUES(140,'*','game','chScrollStatRate','1','Integer','混沌卷轴属性倍数');
INSERT INTO config_server VALUES(141,'*','game','chScrollStatRange','6','Integer','混沌卷的改变范围');
INSERT INTO config_server VALUES(142,'*','game','useUltraNimbleFeet','false','Boolean','新手技能：加大量移速和跳跃');
INSERT INTO config_server VALUES(143,'*','game','useUltraRecovery','false','Boolean','新手技能：回复量大大提升');
INSERT INTO config_server VALUES(144,'*','game','useUltraThreeSnails','false','Boolean','新手技能：投掷蜗牛壳伤害增加');
INSERT INTO config_server VALUES(145,'*','game','useFullAranSkillSet','false','Boolean','战神0转直接解锁所有技能');
INSERT INTO config_server VALUES(146,'*','game','useFastReuseHeroWill','false','Boolean','大大减少战神技能冷却');
INSERT INTO config_server VALUES(147,'*','game','useAntiImmunityCrash','false','Boolean','碰撞技能额外移除怪物的无敌');
INSERT INTO config_server VALUES(148,'*','game','useUnDispelHolyShield','false','Boolean','神圣护盾减少怪物对玩家的伤害');
INSERT INTO config_server VALUES(149,'*','game','useFullHolySymbol','false','Boolean','神圣符不再需要玩家共享经验才能发挥完全的作用');
INSERT INTO config_server VALUES(150,'*','game','useAddSlotsByLevel','false','Boolean','每20级增加背包容量');
INSERT INTO config_server VALUES(151,'*','game','useAddRatesByLevel','false','Boolean','每20级增加个人倍率');
INSERT INTO config_server VALUES(152,'*','game','useStackCouponRates','false','Boolean','经验卡和掉落卡能够叠加');
INSERT INTO config_server VALUES(153,'*','game','usePerfectPitch','false','Boolean','30级后每升一级奖励一个大力币');
INSERT INTO config_server VALUES(154,'*','game','useQuestRate','false','Boolean','独立任务倍率开关');
INSERT INTO config_server VALUES(155,'*','game','questPointRepeatableInterval','25','Integer','可重复任务完成之间的最小间隔，以获得任务点数，默认25h');
INSERT INTO config_server VALUES(156,'*','game','questPointRequirement','0','Integer','多少任务点数加1点声望，默认0不开启任务点数机制');
INSERT INTO config_server VALUES(157,'*','game','questPointPerQuestComplete','0','Integer','完成任务奖励多少任务点数');
INSERT INTO config_server VALUES(158,'*','game','questPointPerEventClear','0','Integer','完成活动事件奖励多少任务点数');
INSERT INTO config_server VALUES(159,'*','game','createGuildMinPartners','6','Integer','创建家族的最小人数');
INSERT INTO config_server VALUES(160,'*','game','createGuildCost','1500000','Integer','创建家族的价格');
INSERT INTO config_server VALUES(161,'*','game','changeEmblemCost','5000000','Integer','更改家族徽章的价格');
INSERT INTO config_server VALUES(162,'*','game','expandGuildBaseCost','500000','Integer','家族扩充的价格');
INSERT INTO config_server VALUES(163,'*','game','expandGuildTierCost','1000000','Integer','扩充家族金币的增值');
INSERT INTO config_server VALUES(164,'*','game','expandGuildMaxCost','5000000','Integer','扩充家族的金币最大值');
INSERT INTO config_server VALUES(165,'*','game','familyRepPerKill','4','Integer','家族杀怪获得多少贡献');
INSERT INTO config_server VALUES(166,'*','game','familyRepPerBossKill','20','Integer','家族击杀boss获得多少贡献');
INSERT INTO config_server VALUES(167,'*','game','familyRepPerLevelUp','200','Integer','家族多少贡献升级');
INSERT INTO config_server VALUES(168,'*','game','familyMaxGenerations','1000','Integer','家族成员的最大人数');
INSERT INTO config_server VALUES(169,'*','game','useEquipmentLevelUpSlots','true','Boolean','装备升级时有可能会得到砸卷次数');
INSERT INTO config_server VALUES(170,'*','game','useEquipmentLevelUpPower','false','Boolean','装备升级时获得属性提升');
INSERT INTO config_server VALUES(171,'*','game','useEquipmentLevelUpCash','false','Boolean','时装也可以升级');
INSERT INTO config_server VALUES(172,'*','game','useSpikesAvoidBanish','false','Boolean','');
INSERT INTO config_server VALUES(173,'*','game','maxEquipmentLevelUpStatUp','1000','Integer','装备升级一次最多增加多少属性');
INSERT INTO config_server VALUES(174,'*','game','maxEquipmentStat','32767','Integer','装备升级最多增加多少属性');
INSERT INTO config_server VALUES(175,'*','game','useEquipmentLevelUp','1','Integer','装备等级上限，1为不能升级');
INSERT INTO config_server VALUES(176,'*','game','useChairExtraHeal','false','Boolean','启用地图椅以进一步恢复玩家的生命值和MP，玩家必须具有椅子精通技能');
INSERT INTO config_server VALUES(177,'*','game','chairExtraHealMultiplier','10','Integer','启用后椅子额外恢复的倍数');
INSERT INTO config_server VALUES(178,'*','game','chairExtraHealMaxDelay','21','Integer','启用后多少秒恢复一次');
INSERT INTO config_server VALUES(179,'*','game','playerNpcInitialX','262','Integer','名人堂玩家形象摆放位置，x坐标');
INSERT INTO config_server VALUES(180,'*','game','playerNpcInitialY','262','Integer','名人堂玩家形象摆放位置，y坐标');
INSERT INTO config_server VALUES(181,'*','game','playerNpcAreaX','320','Integer','名人堂玩家形象摆放横向间隔');
INSERT INTO config_server VALUES(182,'*','game','playerNpcAreaY','320','Integer','名人堂玩家形象摆放纵向间隔');
INSERT INTO config_server VALUES(183,'*','game','playerNpcAreaSteps','4','Integer','短时间内改变名人堂玩家形象的次数');
INSERT INTO config_server VALUES(184,'*','game','playerNpcOrganizeArea','true','Boolean','如果没有空间设置新NPC，则自动重新排列地图上的名人堂玩家NPC。为了解决这个问题，减小了名人堂玩家形象之间的间距。');
INSERT INTO config_server VALUES(185,'*','game','playerNpcAutoDeploy','false','Boolean','满级是否自动成为名人堂玩家，否则需要找一转NPC花费金币进入名人堂');
INSERT INTO config_server VALUES(186,'*','game','useCompulsoryAutoPot','true','Boolean','宠物会消耗尽可能多的药水来恢复到设定值');
INSERT INTO config_server VALUES(187,'*','game','petAutoHpRatio','0.99','Double','宠物回血百分比');
INSERT INTO config_server VALUES(188,'*','game','petAutoMpRatio','0.99','Double','宠物回蓝百分比');
INSERT INTO config_server VALUES(189,'*','game','petExhaustCount','3','Integer','最大宠物数量');
INSERT INTO config_server VALUES(190,'*','game','mountExhaustCount','1','Integer','骑宠的疲劳过程计算，每分钟1次');
INSERT INTO config_server VALUES(191,'*','game','petsNeverHungry','false','Boolean','宠物不会饥饿');
INSERT INTO config_server VALUES(192,'*','game','gmPetsNeverHungry','true','Boolean','GM宠物不会饥饿');
INSERT INTO config_server VALUES(193,'*','game','eventMaxGuildQueue','10','Integer','家族对抗赛最多允许加入的队列人数');
INSERT INTO config_server VALUES(194,'*','game','eventLobbyDelay','10','Integer','打开每个活动事件对话的冷却时间，单位s');
INSERT INTO config_server VALUES(195,'*','game','useFastDojoUpgrade','false','Boolean','是否开启道馆快速升级');
INSERT INTO config_server VALUES(196,'*','game','useDeadlyDojo','false','Boolean','是否开启道馆快速升级');
INSERT INTO config_server VALUES(197,'*','game','dojoEnergyAtk','100','Integer','攻击获得道场能量');
INSERT INTO config_server VALUES(198,'*','game','dojoEnergyDmg','20','Integer','承伤获得道场能量');
INSERT INTO config_server VALUES(199,'*','game','weddingReservationDelay','3','Integer','允许婚礼预定的最小数量');
INSERT INTO config_server VALUES(200,'*','game','weddingReservationTimeout','10','Integer','婚礼预定的超时时间，默认10min');
INSERT INTO config_server VALUES(201,'*','game','weddingReservationInterval','60','Integer','婚礼持续时间，默认60min');
INSERT INTO config_server VALUES(202,'*','game','weddingBlessExp','30000','Integer','婚礼祝福获取的经验');
INSERT INTO config_server VALUES(203,'*','game','weddingGiftLimit','1','Integer','每个人最多只能送出一份结婚礼物');
INSERT INTO config_server VALUES(204,'*','game','weddingBlesserShowFx','true','Boolean','是否显示玩家的婚礼祝福');
INSERT INTO config_server VALUES(205,'*','game','useBuybackSystem','false','Boolean','是否启用买活系统');
INSERT INTO config_server VALUES(206,'*','game','useBuybackWithMesos','false','Boolean','是否用金币买活，否则用点券');
INSERT INTO config_server VALUES(207,'*','game','buybackFee','77.70','Double','买活的基本花费，30级前买活都是固定的');
INSERT INTO config_server VALUES(208,'*','game','buybackLevelStackFee','85.47','Double','每增长一级买活增长的花费，直到120级达到最高');
INSERT INTO config_server VALUES(209,'*','game','buybackMesoMultiplier','1000','Integer','金币买活花费的倍数');
INSERT INTO config_server VALUES(210,'*','game','buybackReturnMinutes','1','Integer','玩家能在死亡几min内买活');
INSERT INTO config_server VALUES(211,'*','game','buybackCoolDownMinutes','7','Integer','买活的冷却时间，单位min');
INSERT INTO config_server VALUES(212,'*','game','timeoutDuration','3600000','Long','每隔多少ms，移除与服务端断连的客户端');
INSERT INTO config_server VALUES(213,'*','game','eventEndTimestamp','4091679622000','Long','活动事件结束的时间戳');
INSERT INTO config_server VALUES(214,'*','game','buyFameFee','0','Integer','购买1点人气消耗的金币，为0时不能购买');
INSERT INTO config_server VALUES(215,'*','game','bmMobRate','1','Integer','怪物倍率，最高10倍。小于等于0默认1倍怪，大于10倍默认10倍怪');
INSERT INTO config_server VALUES(216,'*','game','useEnforceSpecifyLevelExpRate','0','Integer','指定某个等级之后强制使用1倍的经验倍率');
INSERT INTO config_server VALUES(217,'*','game','playerLevelUpBroadcast','true','Boolean','是否启用升级全服广播');
INSERT INTO config_server VALUES(218,'*','game','isKnightsOfCygnus','true','Boolean','是否开启骑士团职业');
INSERT INTO config_server VALUES(219,'*','game','isAran','true','Boolean','是否开启英雄职业');
INSERT INTO config_server VALUES(220,'*','game','hiredMerchantExpRate','0.0','Double','雇佣商店增加的经验率，小于等0不生效');
INSERT INTO config_server VALUES(221,'*','game','pickedEquipRandomValue','0','Integer','捡起的装备上下浮动的值，只浮动不为0的属性');
INSERT INTO config_server VALUES(222,'*','game','pickedEquipRandomOpenLevel','0','Integer','捡起的装备上下浮动开启的等级');
COMMIT;

BEGIN TRANSACTION;
CREATE TABLE config_gmcommand
(

    id               INTEGER PRIMARY KEY,

    command     VARCHAR(30),

    gm_level      INTEGER,

    is_work      VARCHAR(10),

    command_class_name      VARCHAR(30),

    description      VARCHAR(500),

    gm_level_primitive      INTEGER

);
INSERT INTO config_gmCommand VALUES(1,'help',0,'true','HelpCommand','帮助指令，输出所有可用指令列表',0);
INSERT INTO config_gmCommand VALUES(2,'commands',0,'true','HelpCommand','帮助指令，输出所有可用指令列表',0);
INSERT INTO config_gmCommand VALUES(3,'droplimit',0,'true','DropLimitCommand','查看服务器最大掉落物数量',0);
INSERT INTO config_gmCommand VALUES(4,'time',0,'true','TimeCommand','显示服务器时间',0);
INSERT INTO config_gmCommand VALUES(5,'buyback',0,'true','BuyBackCommand','买活指令，死亡后可以立即买活',0);
INSERT INTO config_gmCommand VALUES(6,'gacha',0,'true','GachaCommand','查询扭蛋机部分奖励列表',0);
INSERT INTO config_gmCommand VALUES(7,'dispose',0,'true','DisposeCommand','解卡指令，客户端异常时可以解卡',0);
INSERT INTO config_gmCommand VALUES(8,'equiplv',0,'true','EquipLvCommand','显示装备等级',0);
INSERT INTO config_gmCommand VALUES(9,'rates',0,'true','ShowRatesCommand','倍率查看',0);
INSERT INTO config_gmCommand VALUES(10,'online',0,'true','OnlineCommand','查询在线人数，人物所在位置',0);
INSERT INTO config_gmCommand VALUES(11,'bug',0,'true','ReportBugCommand','给GM反馈BUG',0);
INSERT INTO config_gmCommand VALUES(12,'points',0,'true','ReadPointsCommand','查询奖励点数和投票点数，暂时没发现有什么用',0);
INSERT INTO config_gmCommand VALUES(13,'event',0,'true','JoinEventCommand','参加或离开活动',0);
INSERT INTO config_gmCommand VALUES(14,'ranks',0,'true','RanksCommand','查看排名',0);
INSERT INTO config_gmCommand VALUES(15,'autoadd',0,'true','AutoAddCommand','自动加点',0);
INSERT INTO config_gmCommand VALUES(16,'toggleexp',0,'true','ToggleExpCommand','切换是否获取经验',0);
INSERT INTO config_gmCommand VALUES(17,'mapowner',0,'true','MapOwnerClaimCommand','查询地图归属',0);
INSERT INTO config_gmCommand VALUES(18,'map',0,'true','MapIdCommand','查看地图id',0);
INSERT INTO config_gmCommand VALUES(19,'buyfame',0,'true','BuyFameCommand','购买人气',0);
INSERT INTO config_gmCommand VALUES(20,'pfp',0,'true','PfpCommand','启动宠物全屏拣取:',0);
INSERT INTO config_gmCommand VALUES(21,'bosshp',1,'true','BossHpCommand','显示BOSS血量',1);
INSERT INTO config_gmCommand VALUES(22,'mobhp',1,'true','MobHpCommand','显示怪物血量',1);
INSERT INTO config_gmCommand VALUES(23,'whatdropsfrom',1,'true','WhatDropsFromCommand','查询怪物掉落的物品',1);
INSERT INTO config_gmCommand VALUES(24,'whodrops',1,'true','WhoDropsCommand','查询物品掉落的怪物',1);
INSERT INTO config_gmCommand VALUES(25,'buffme',1,'true','BuffMeCommand','给自己管理员祝福',1);
INSERT INTO config_gmCommand VALUES(26,'goto',1,'true','GotoCommand','移动到指定地图',1);
INSERT INTO config_gmCommand VALUES(27,'recharge',2,'true','RechargeCommand','充能您的使用道具。',2);
INSERT INTO config_gmCommand VALUES(28,'whereami',2,'true','WhereaMiCommand','查询当前地图中的玩家及NPC',2);
INSERT INTO config_gmCommand VALUES(29,'hide',2,'true','HideCommand','隐身',2);
INSERT INTO config_gmCommand VALUES(30,'unhide',2,'true','UnHideCommand','解除隐身',2);
INSERT INTO config_gmCommand VALUES(31,'sp',2,'true','SpCommand','增加技能点',2);
INSERT INTO config_gmCommand VALUES(32,'ap',2,'true','ApCommand','增加能力点数',2);
INSERT INTO config_gmCommand VALUES(33,'empowerme',2,'true','EmpowerMeCommand','使用更多的buff强化自己',2);
INSERT INTO config_gmCommand VALUES(34,'buffmap',2,'true','BuffMapCommand','地图所有玩家获得Buff',2);
INSERT INTO config_gmCommand VALUES(35,'buff',2,'true','BuffCommand','给自己使用BUFF技能',2);
INSERT INTO config_gmCommand VALUES(36,'bomb',2,'true','BombCommand','使用炸弹攻击玩家',2);
INSERT INTO config_gmCommand VALUES(37,'dc',2,'true','DcCommand','将指定玩家踢下线',2);
INSERT INTO config_gmCommand VALUES(38,'cleardrops',2,'true','ClearDropsCommand','清除丢弃的物品',2);
INSERT INTO config_gmCommand VALUES(39,'clearslot',2,'true','ClearSlotCommand','清理自己的背包',2);
INSERT INTO config_gmCommand VALUES(40,'clearsavelocs',2,'true','ClearSavedLocationsCommand','清除玩家保存的位置',2);
INSERT INTO config_gmCommand VALUES(41,'warp',2,'true','WarpCommand','将玩家传送到指定地图。',2);
INSERT INTO config_gmCommand VALUES(42,'warphere',2,'true','SummonCommand','将另一个玩家传送到您所在的地图。',2);
INSERT INTO config_gmCommand VALUES(43,'warpto',2,'true','ReachCommand','查询玩家在几线',2);
INSERT INTO config_gmCommand VALUES(44,'summon',2,'true','SummonCommand','将另一个玩家传送到您所在的地图。',2);
INSERT INTO config_gmCommand VALUES(45,'reach',2,'true','ReachCommand','查询玩家在几线',2);
INSERT INTO config_gmCommand VALUES(46,'follow',2,'true','ReachCommand','查询玩家在几线',2);
INSERT INTO config_gmCommand VALUES(47,'gmshop',2,'true','GmShopCommand','打开GM商店',2);
INSERT INTO config_gmCommand VALUES(48,'heal',2,'true','HealCommand','治疗自己',2);
INSERT INTO config_gmCommand VALUES(49,'item',2,'true','ItemCommand','添加物品',2);
INSERT INTO config_gmCommand VALUES(50,'drop',2,'true','ItemDropCommand','添加掉落',2);
INSERT INTO config_gmCommand VALUES(51,'level',2,'true','LevelCommand','设置等级 可降级',2);
INSERT INTO config_gmCommand VALUES(52,'levelpro',2,'true','LevelProCommand','提高等级 不可降级',2);
INSERT INTO config_gmCommand VALUES(53,'setslot',2,'true','SetSlotCommand','设置玩家的背包槽位数量。',2);
INSERT INTO config_gmCommand VALUES(54,'setstat',2,'true','SetStatCommand','设置玩家的属性点数。',2);
INSERT INTO config_gmCommand VALUES(55,'maxstat',2,'true','MaxStatCommand','最高等级及属性',2);
INSERT INTO config_gmCommand VALUES(56,'maxskill',2,'true','MaxSkillCommand','技能全满',2);
INSERT INTO config_gmCommand VALUES(57,'resetskill',2,'true','ResetSkillCommand','重置技能点',2);
INSERT INTO config_gmCommand VALUES(58,'search',2,'true','SearchCommand','暂无描述',2);
INSERT INTO config_gmCommand VALUES(59,'jail',2,'true','JailCommand','将玩家关进监狱',2);
INSERT INTO config_gmCommand VALUES(60,'unjail',2,'true','UnJailCommand','释放监狱玩家',2);
INSERT INTO config_gmCommand VALUES(61,'job',2,'true','JobCommand','改变职业',2);
INSERT INTO config_gmCommand VALUES(62,'unbug',2,'true','UnBugCommand','解决地图中的卡bug问题。',2);
INSERT INTO config_gmCommand VALUES(63,'id',2,'true','IdCommand','查询物品的ID。',2);
INSERT INTO config_gmCommand VALUES(64,'gachalist',2,'true','GachaListCommand','查询宝箱物品',2);
INSERT INTO config_gmCommand VALUES(65,'loot',2,'true','LootCommand','拾取所有属于你的物品',2);
INSERT INTO config_gmCommand VALUES(66,'debuff',3,'true','DebuffCommand','对地图上的玩家施加不同的异常状态。',3);
INSERT INTO config_gmCommand VALUES(67,'fly',3,'true','FlyCommand','启用或禁用玩家的飞行功能。',3);
INSERT INTO config_gmCommand VALUES(68,'spawn',3,'true','SpawnCommand','生成怪物到玩家当前位置。',3);
INSERT INTO config_gmCommand VALUES(69,'mutemap',3,'true','MuteMapCommand','将当前地图静音或取消静音。',3);
INSERT INTO config_gmCommand VALUES(70,'checkdmg',3,'true','CheckDmgCommand','检查玩家的最大基础伤害（在技能之前）。',3);
INSERT INTO config_gmCommand VALUES(71,'inmap',3,'true','InMapCommand','查看当前地图上的所有玩家。',3);
INSERT INTO config_gmCommand VALUES(72,'reloadevents',3,'true','ReloadEventsCommand','重新加载事件脚本',3);
INSERT INTO config_gmCommand VALUES(73,'reloaddrops',3,'true','ReloadDropsCommand','重新加载怪物掉落数据。',3);
INSERT INTO config_gmCommand VALUES(74,'reloadportals',3,'true','ReloadPortalsCommand','重新加载传送门脚本。',3);
INSERT INTO config_gmCommand VALUES(75,'reloadmap',3,'true','ReloadMapCommand','重新加载当前地图。',3);
INSERT INTO config_gmCommand VALUES(76,'reloadshops',3,'true','ReloadShopsCommand','重新加载商店脚本。',3);
INSERT INTO config_gmCommand VALUES(77,'hpmp',3,'true','HpMpCommand','为指定玩家恢复HP和MP或修改HP和MP值。',3);
INSERT INTO config_gmCommand VALUES(78,'maxhpmp',3,'true','MaxHpMpCommand','设置自己或其他玩家的最大HP和MP值。',3);
INSERT INTO config_gmCommand VALUES(79,'music',3,'true','MusicCommand','播放指定的游戏音乐。',3);
INSERT INTO config_gmCommand VALUES(80,'monitor',3,'true','MonitorCommand','监视或停止监视玩家的活动。',3);
INSERT INTO config_gmCommand VALUES(81,'monitors',3,'true','MonitorsCommand','列出当前正在被监视的玩家。',3);
INSERT INTO config_gmCommand VALUES(82,'ignore',3,'true','IgnoreCommand','在游戏中忽略或取消忽略指定的玩家。',3);
INSERT INTO config_gmCommand VALUES(83,'ignored',3,'true','IgnoredCommand','暂无描述',3);
INSERT INTO config_gmCommand VALUES(84,'pos',3,'true','PosCommand','获取玩家当前位置信息和Foothold ID。',3);
INSERT INTO config_gmCommand VALUES(85,'togglecoupon',3,'true','ToggleCouponCommand','在服务器上切换优惠券（Coupon）的状态。',3);
INSERT INTO config_gmCommand VALUES(86,'togglewhitechat',3,'true','ChatCommand','切换聊天模式。',3);
INSERT INTO config_gmCommand VALUES(87,'fame',3,'true','FameCommand','更改玩家的声望（Fame）值。',3);
INSERT INTO config_gmCommand VALUES(88,'givenx',3,'true','GiveNxCommand','添加点券',3);
INSERT INTO config_gmCommand VALUES(89,'givevp',3,'true','GiveVpCommand','向玩家授予投票点（Vote Points）。',3);
INSERT INTO config_gmCommand VALUES(90,'givems',3,'true','GiveMesosCommand','添加金币',3);
INSERT INTO config_gmCommand VALUES(91,'giverp',3,'true','GiveRpCommand','向玩家授予奖励点（Reward Points）。',3);
INSERT INTO config_gmCommand VALUES(92,'expeds',3,'true','ExpedsCommand','列出服务器中各频道的远征队伍信息。',3);
INSERT INTO config_gmCommand VALUES(93,'kill',3,'true','KillCommand','杀死玩家',3);
INSERT INTO config_gmCommand VALUES(94,'seed',3,'true','SeedCommand','在HPQ地图中生成种子物品。',3);
INSERT INTO config_gmCommand VALUES(95,'maxenergy',3,'true','MaxEnergyCommand','最大道馆能量',3);
INSERT INTO config_gmCommand VALUES(96,'killall',3,'true','KillAllCommand','清怪掉落',3);
INSERT INTO config_gmCommand VALUES(97,'notice',3,'true','NoticeCommand','发送服务器公告。',3);
INSERT INTO config_gmCommand VALUES(98,'rip',3,'true','RipCommand','发送RIP消息。',3);
INSERT INTO config_gmCommand VALUES(99,'openportal',3,'true','OpenPortalCommand','打开指定传送门。',3);
INSERT INTO config_gmCommand VALUES(100,'closeportal',3,'true','ClosePortalCommand','关闭指定地图上的传送门。',3);
INSERT INTO config_gmCommand VALUES(101,'pe',3,'true','PeCommand','模拟接收特定封包以进行调试。',3);
INSERT INTO config_gmCommand VALUES(102,'startevent',3,'true','StartEventCommand','在当前地图启动一个事件，可以设置参与玩家数量。',3);
INSERT INTO config_gmCommand VALUES(103,'endevent',3,'true','EndEventCommand','结束服务器上正在进行的事件。',3);
INSERT INTO config_gmCommand VALUES(104,'startmapevent',3,'true','StartMapEventCommand','在当前地图启动一个事件。',3);
INSERT INTO config_gmCommand VALUES(105,'stopmapevent',3,'true','StopMapEventCommand','停止当前地图上正在进行的事件。',3);
INSERT INTO config_gmCommand VALUES(106,'online2',3,'true','OnlineTwoCommand','暂无描述',3);
INSERT INTO config_gmCommand VALUES(107,'ban',3,'true','BanCommand','禁止玩家访问服务器并记录原因。',3);
INSERT INTO config_gmCommand VALUES(108,'unban',3,'true','UnBanCommand','解除封禁某个玩家。',3);
INSERT INTO config_gmCommand VALUES(109,'healmap',3,'true','HealMapCommand','恢复当前地图上所有角色的健康（HP和MP）。',3);
INSERT INTO config_gmCommand VALUES(110,'healperson',3,'true','HealPersonCommand','为指定玩家恢复健康（HP和MP）。',3);
INSERT INTO config_gmCommand VALUES(111,'hurt',3,'true','HurtCommand','伤害指定玩家的1点HP。',3);
INSERT INTO config_gmCommand VALUES(112,'killmap',3,'true','KillMapCommand','杀死当前地图上的所有玩家。',3);
INSERT INTO config_gmCommand VALUES(113,'night',3,'true','NightCommand','在当前地图上触发夜晚效果。',3);
INSERT INTO config_gmCommand VALUES(114,'npc',3,'true','NpcCommand','生成NPC并放置在玩家位置。',3);
INSERT INTO config_gmCommand VALUES(115,'face',3,'true','FaceCommand','更改玩家的面部表情（Face）ID。',3);
INSERT INTO config_gmCommand VALUES(116,'hair',3,'true','HairCommand','更改玩家的发型。',3);
INSERT INTO config_gmCommand VALUES(117,'startquest',3,'true','QuestStartCommand','启动指定任务。',3);
INSERT INTO config_gmCommand VALUES(118,'completequest',3,'true','QuestCompleteCommand','强制完成指定任务。',3);
INSERT INTO config_gmCommand VALUES(119,'resetquest',3,'true','QuestResetCommand','重置指定任务的进度。',3);
INSERT INTO config_gmCommand VALUES(120,'timer',3,'true','TimerCommand','为指定玩家设置计时器或删除计时器。',3);
INSERT INTO config_gmCommand VALUES(121,'timermap',3,'true','TimerMapCommand','在游戏地图中为所有玩家设置计时器或删除计时器。',3);
INSERT INTO config_gmCommand VALUES(122,'timerall',3,'true','TimerAllCommand','为所有玩家设置计时器或删除计时器。',3);
INSERT INTO config_gmCommand VALUES(123,'warpmap',3,'true','WarpMapCommand','将当前地图中的所有玩家传送到指定地图。',2);
INSERT INTO config_gmCommand VALUES(124,'warparea',3,'true','WarpAreaCommand','将附近的玩家传送到指定地图。',2);
INSERT INTO config_gmCommand VALUES(125,'gotonpc',3,'true','GotoNpcCommand','进入npcid对应的地图',3);
INSERT INTO config_gmCommand VALUES(126,'xiguai',3,'true','SuckMonsterCommand','开启或关闭地图吸怪',3);
INSERT INTO config_gmCommand VALUES(127,'servermessage',4,'true','ServerMessageCommand','设置服务器的公告信息。',4);
INSERT INTO config_gmCommand VALUES(128,'proitem',4,'true','ProItemCommand','为自己创建一个具有指定属性的装备。',4);
INSERT INTO config_gmCommand VALUES(129,'seteqstat',4,'true','SetEqStatCommand','为玩家的所有装备设置统一的属性值（如力量、敏捷、生命等）和速度跳跃属性值。',4);
INSERT INTO config_gmCommand VALUES(130,'exprate',4,'true','ExpRateCommand','更改游戏服务器的经验倍率。',4);
INSERT INTO config_gmCommand VALUES(131,'mesorate',4,'true','MesoRateCommand','更改服务器的金币倍率。',4);
INSERT INTO config_gmCommand VALUES(132,'droprate',4,'true','DropRateCommand','更改游戏服务器的掉落率。',4);
INSERT INTO config_gmCommand VALUES(133,'bossdroprate',4,'true','BossDropRateCommand','设置服务器的Boss掉落率。',4);
INSERT INTO config_gmCommand VALUES(134,'questrate',4,'true','QuestRateCommand','更改服务器的任务倍率。',4);
INSERT INTO config_gmCommand VALUES(135,'travelrate',4,'true','TravelRateCommand','设置旅行速度倍率。',4);
INSERT INTO config_gmCommand VALUES(136,'fishrate',4,'true','FishingRateCommand','更改游戏服务器的钓鱼概率倍率。',4);
INSERT INTO config_gmCommand VALUES(137,'itemvac',4,'true','ItemVacCommand','吸取玩家周围的所有物品。',4);
INSERT INTO config_gmCommand VALUES(138,'forcevac',4,'true','ForceVacCommand','强制吸取地图上的所有物品。',4);
INSERT INTO config_gmCommand VALUES(139,'zakum',4,'true','ZakumCommand','召唤扎昆怪物。',4);
INSERT INTO config_gmCommand VALUES(140,'horntail',4,'true','HorntailCommand','在玩家当前位置生成暗黑龙王。',4);
INSERT INTO config_gmCommand VALUES(141,'pinkbean',4,'true','PinkbeanCommand','在玩家位置下方生成Pinkbean BOSS怪物。',4);
INSERT INTO config_gmCommand VALUES(142,'pap',4,'true','PapCommand','在玩家位置下方生成Papulatus BOSS怪物。',4);
INSERT INTO config_gmCommand VALUES(143,'pianus',4,'true','PianusCommand','在玩家位置下方生成Pianus BOSS怪物。',4);
INSERT INTO config_gmCommand VALUES(144,'cake',4,'true','CakeCommand','在游戏地图中生成一个蛋糕怪物。',4);
INSERT INTO config_gmCommand VALUES(145,'playernpc',4,'true','PlayerNpcCommand','在当前地图生成一个玩家NPC。',4);
INSERT INTO config_gmCommand VALUES(146,'playernpcremove',4,'true','PlayerNpcRemoveCommand','从当前地图移除一个玩家NPC。',4);
INSERT INTO config_gmCommand VALUES(147,'pnpc',4,'true','PnpcCommand','在当前地图创建npc',4);
INSERT INTO config_gmCommand VALUES(148,'pnpcremove',4,'true','PnpcRemoveCommand','移除当前地图创建的NPC',4);
INSERT INTO config_gmCommand VALUES(149,'pmob',4,'true','PmobCommand','在当前地图创建怪物',4);
INSERT INTO config_gmCommand VALUES(150,'pmobremove',4,'true','PmobRemoveCommand','移除当前地图创建的怪物',4);
INSERT INTO config_gmCommand VALUES(151,'debug',5,'true','DebugCommand','暂无描述',5);
INSERT INTO config_gmCommand VALUES(152,'set',5,'true','SetCommand','暂无描述',5);
INSERT INTO config_gmCommand VALUES(153,'showpackets',5,'true','ShowPacketsCommand','开启/关闭封包信息',5);
INSERT INTO config_gmCommand VALUES(154,'showmovelife',5,'true','ShowMoveLifeCommand','开启/关闭生物移动信息',5);
INSERT INTO config_gmCommand VALUES(155,'showsessions',5,'true','ShowSessionsCommand','暂无描述',5);
INSERT INTO config_gmCommand VALUES(156,'iplist',5,'true','IpListCommand','暂无描述',5);
INSERT INTO config_gmCommand VALUES(157,'setgmlevel',6,'true','SetGmLevelCommand','设置GM等级',6);
INSERT INTO config_gmCommand VALUES(158,'warpworld',6,'true','WarpWorldCommand','迁移大区 ',6);
INSERT INTO config_gmCommand VALUES(159,'saveall',6,'true','SaveAllCommand','保存',6);
INSERT INTO config_gmCommand VALUES(160,'dcall',6,'true','DCAllCommand','将所有玩家踢下线',6);
INSERT INTO config_gmCommand VALUES(161,'mapplayers',6,'true','MapPlayersCommand','显示地图中的玩家',6);
INSERT INTO config_gmCommand VALUES(162,'getacc',6,'true','GetAccCommand','获取玩家账号',6);
INSERT INTO config_gmCommand VALUES(163,'shutdown',6,'true','ShutdownCommand','关闭服务器',6);
INSERT INTO config_gmCommand VALUES(164,'clearquestcache',6,'true','ClearQuestCacheCommand','清除任务缓存',6);
INSERT INTO config_gmCommand VALUES(165,'clearquest',6,'true','ClearQuestCommand','清除单个任务缓存',6);
INSERT INTO config_gmCommand VALUES(166,'supplyratecoupon',6,'true','SupplyRateCouponCommand','允许/禁止现金商店出售利率券',6);
INSERT INTO config_gmCommand VALUES(167,'spawnallpnpcs',6,'true','SpawnAllPNpcsCommand','暂无描述',6);
INSERT INTO config_gmCommand VALUES(168,'eraseallpnpcs',6,'true','EraseAllPNpcsCommand','清除所有的NPC',6);
INSERT INTO config_gmCommand VALUES(169,'addchannel',6,'true','ServerAddChannelCommand','添加频道',6);
INSERT INTO config_gmCommand VALUES(170,'addworld',6,'true','ServerAddWorldCommand','创建大区',6);
INSERT INTO config_gmCommand VALUES(171,'removechannel',6,'true','ServerRemoveChannelCommand','移除大区的最后一个频道',6);
INSERT INTO config_gmCommand VALUES(172,'removeworld',6,'true','ServerRemoveWorldCommand','移除大区',6);
INSERT INTO config_gmCommand VALUES(173, 'shtj', 0, 'true', 'DamageStatisticsCommand', '伤害统计', 0);
INSERT INTO config_gmCommand VALUES(174, 'gohere', 1, 'true', 'GoHereCommand', '查询地图，并选择传送', 1);

COMMIT;


BEGIN TRANSACTION;
CREATE TABLE kook_config
(
    config_name      VARCHAR(20),
    config_data      VARCHAR(100)
);
INSERT INTO kook_config VALUES('botToken', NULL);
INSERT INTO kook_config VALUES('guildId', NULL);
INSERT INTO kook_config VALUES('guildName', NULL);
INSERT INTO kook_config VALUES('channelId', NULL);
INSERT INTO kook_config VALUES('channelName', '绑定频道');
INSERT INTO kook_config VALUES('wsUrl', NULL);
INSERT INTO kook_config VALUES('bindKeywords', '绑定');
COMMIT;

BEGIN TRANSACTION;
alter table config_server add column popular varchar(5) default null;
alter table config_server add column simple_name varchar(10) default null;
COMMIT;
